# code: language=yaml insertSpaces=true tabSize=2
name: lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-gha:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4

      - name: install actionlint-matcher
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
