# code: language=yaml insertSpaces=true tabSize=2
name: lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
# id-token: write
# issues: write
# pull-requests: write

jobs:
  lint-gha:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
