# code: language=yaml insertSpaces=true tabSize=2
name: publish GitHub Pages site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4

      - name: set up GitHub Pages
        uses: actions/configure-pages@v5

      - name: build site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./pages
          destination: ./_site

      - name: upload rendered site
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: deploy site
        id: deployment
        uses: actions/deploy-pages@v4
